# fly.toml app configuration file generated for ai-dungeon-master on 2026-06-04T15:16:12+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-dungeon-master'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[env]
  APP_LOG_PERSIST_ENABLED = 'true'
  GAME_SESSION_STORE_DIR = '/data/sessions'
  PORT = '8080'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '20s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
