import type { WorldState } from './types'

export function createInitialWorldState(): WorldState {
  return {
    rooms: {
      '1': {
        id: '1',
        name: 'Entree exterieure',
        description: 'Le chemin d arrivee, les grandes portes et Mac le pommier eveille.',
        tags: ['outside', 'safe', 'mac'],
        exits: ['2', '4'],
      },
      '2': {
        id: '2',
        name: 'Verger de pommiers',
        description: 'Un verger nerveux ou la dryade surveille les intrus.',
        tags: ['orchard', 'social', 'route_hint'],
        exits: ['1', '7'],
      },
      '3': {
        id: '3',
        name: 'Tas de dechets',
        description: 'Un coin humide ou des champignons violets reagissent au contact.',
        tags: ['hazard', 'trap'],
        exits: ['7', '8'],
      },
      '4': {
        id: '4',
        name: 'Entree de la boulangerie',
        description: 'Le vestibule interieur, poussiereux, qui distribue vers les salles plus dangereuses.',
        tags: ['bakery', 'crossroads'],
        exits: ['1', '5', '8', '9'],
      },
      '5': {
        id: '5',
        name: 'Bureau de Grammy',
        description: 'Un bureau serre, couvert de paperasse et de cachettes de proprietaire prudente.',
        tags: ['office', 'recipe_cache'],
        exits: ['4', '8'],
      },
      '7': {
        id: '7',
        name: 'Quai de chargement',
        description: 'Une entree laterale avec des caisses, de la farine renversee et un angle discret.',
        tags: ['dock', 'stealth_route'],
        exits: ['2', '3', '8'],
      },
      '8': {
        id: '8',
        name: 'Sol de la boulangerie',
        description: 'Le coeur brulant du batiment, entre fours enchantes et outils trop agites.',
        tags: ['bakery_floor', 'danger'],
        exits: ['4', '5', '7', '9'],
      },
      '9': {
        id: '9',
        name: 'Appartement de Grammy',
        description: 'La partie habitee, fouillee par les gobelins, ou les souvenirs de Grammy resistent encore.',
        tags: ['apartment', 'boss', 'recipe_cache'],
        exits: ['4', '8'],
      },
    },
    objects: {
      front_double_door: {
        id: 'front_double_door',
        roomId: '4',
        name: 'double porte de la boulangerie',
        aliases: ['porte d entree', 'portes d entree', 'grandes portes', 'battants'],
        kind: 'door',
        visible: true,
        discovered: true,
        opened: false,
        locked: false,
        tags: ['door', 'street'],
        description: 'La double porte qui separe la boutique de la rue.',
      },
      reserve_door: {
        id: 'reserve_door',
        roomId: '4',
        name: 'porte de la reserve',
        aliases: ['porte des reserves', 'porte interieure', 'porte vers les fours'],
        kind: 'door',
        visible: true,
        discovered: true,
        opened: false,
        locked: false,
        tags: ['door', 'bakery'],
        description: 'Une porte interieure qui mene vers la reserve enfarinee.',
      },
      office_desk: {
        id: 'office_desk',
        roomId: '5',
        name: 'bureau de Grammy',
        aliases: ['bureau', 'paperasse', 'registres'],
        kind: 'fixture',
        visible: true,
        discovered: true,
        used: false,
        contains: ['office_drawer'],
        tags: ['searchable', 'office', 'recipe_cache'],
        dc: { search: 10 },
        description: 'Un bureau trop petit pour autant de factures, de miettes et de secrets.',
      },
      office_drawer: {
        id: 'office_drawer',
        roomId: '5',
        name: 'tiroir du bureau',
        aliases: ['tiroir', 'tiroir bas', 'tiroir coince'],
        kind: 'container',
        visible: false,
        discovered: false,
        opened: false,
        locked: true,
        contains: ['recipe_half_office'],
        tags: ['drawer', 'recipe_cache'],
        dc: { search: 12, unlock: 12, force: 13 },
        description: 'Un tiroir bas, coince sous des factures graisseuses.',
      },
      recipe_half_office: {
        id: 'recipe_half_office',
        roomId: '5',
        name: 'moitie de recette du bureau',
        aliases: ['recette', 'fragment de recette', 'papier brule', 'parchemin'],
        kind: 'clue',
        visible: false,
        discovered: false,
        taken: false,
        tags: ['recipe_half', 'quest_item', 'readable'],
        description: 'Un fragment de recette au coin brule.',
        readableText: 'La premiere moitie parle de pommes, de cannelle et d un temps de cuisson impossible.',
      },
      office_register: {
        id: 'office_register',
        roomId: '5',
        name: 'registre de commandes',
        aliases: ['registre', 'livre de comptes', 'commandes'],
        kind: 'clue',
        visible: true,
        discovered: true,
        taken: false,
        tags: ['readable', 'hint'],
        description: 'Un registre tache ou Grammy notait ses livraisons.',
        readableText: 'Les dernieres lignes mentionnent le quai de chargement et une livraison interrompue.',
      },
      dock_crates: {
        id: 'dock_crates',
        roomId: '7',
        name: 'caisses du quai',
        aliases: ['caisses', 'caisse', 'marchandises'],
        kind: 'container',
        visible: true,
        discovered: true,
        opened: false,
        locked: false,
        contains: ['rusty_key', 'dock_delivery_note'],
        tags: ['container', 'dock', 'searchable'],
        dc: { search: 9 },
        description: 'Des caisses bousculees, marquees du sceau de Grammy.',
      },
      rusty_key: {
        id: 'rusty_key',
        roomId: '7',
        name: 'cle rouillee',
        aliases: ['cle', 'clef', 'petite cle'],
        kind: 'item',
        visible: false,
        discovered: false,
        taken: false,
        tags: ['key'],
        description: 'Une petite cle rouillee qui sent la farine humide.',
      },
      dock_delivery_note: {
        id: 'dock_delivery_note',
        roomId: '7',
        name: 'bon de livraison',
        aliases: ['bon', 'note', 'papier de livraison'],
        kind: 'clue',
        visible: false,
        discovered: false,
        taken: false,
        tags: ['readable', 'hint'],
        description: 'Un bon de livraison froisse.',
        readableText: 'La livraison etait destinee aux fours, mais quelqu un a note: passer par l arriere si les gobelins chantent.',
      },
      enchanted_oven: {
        id: 'enchanted_oven',
        roomId: '8',
        name: 'four enchante',
        aliases: ['four', 'fours', 'fournee', 'runes du four'],
        kind: 'fixture',
        visible: true,
        discovered: true,
        used: false,
        opened: false,
        locked: false,
        tags: ['oven', 'dangerous', 'noise'],
        dc: { open: 12 },
        description: 'Un four trop chaud, grave de runes de cuisine.',
      },
      animated_knife_rack: {
        id: 'animated_knife_rack',
        roomId: '8',
        name: 'ratelier de couteaux animes',
        aliases: ['couteaux', 'ratelier', 'outils animes'],
        kind: 'trap',
        visible: true,
        discovered: true,
        used: false,
        disarmed: false,
        tags: ['trap', 'noise', 'dangerous'],
        dc: { search: 12, unlock: 13 },
        description: 'Des couteaux qui vibrent dans leur ratelier comme s ils attendaient un ordre.',
      },
      flour_sacks: {
        id: 'flour_sacks',
        roomId: '8',
        name: 'sacs de farine effondres',
        aliases: ['sacs', 'farine', 'tas de farine'],
        kind: 'container',
        visible: true,
        discovered: true,
        opened: false,
        locked: false,
        contains: ['flour_handprints'],
        tags: ['searchable', 'hint'],
        dc: { search: 10 },
        description: 'Des sacs eventres avec des traces de petites mains.',
      },
      flour_handprints: {
        id: 'flour_handprints',
        roomId: '8',
        name: 'traces de farine gobelines',
        aliases: ['traces', 'empreintes', 'mains farineuses'],
        kind: 'clue',
        visible: false,
        discovered: false,
        taken: false,
        tags: ['hint'],
        description: 'Des empreintes qui montent vers l appartement.',
      },
      violet_fungus_heap: {
        id: 'violet_fungus_heap',
        roomId: '3',
        name: 'amas de champignons violets',
        aliases: ['champignons', 'champignon violet', 'amas violet', 'tas de champignons'],
        kind: 'trap',
        visible: true,
        discovered: true,
        used: false,
        disarmed: false,
        tags: ['trap', 'poison'],
        dc: { search: 13, unlock: 14 },
        description: 'Des champignons mous qui fremissent quand on approche.',
      },
      grammy_armoire: {
        id: 'grammy_armoire',
        roomId: '9',
        name: 'armoire de Grammy',
        aliases: ['armoire', 'placard', 'linges'],
        kind: 'container',
        visible: true,
        discovered: true,
        opened: false,
        locked: false,
        contains: ['recipe_half_apartment'],
        tags: ['armoire', 'recipe_cache'],
        dc: { search: 10 },
        description: 'Une armoire haute dont la porte ferme mal.',
      },
      recipe_half_apartment: {
        id: 'recipe_half_apartment',
        roomId: '9',
        name: 'moitie de recette de Grammy',
        aliases: ['recette', 'fragment de recette', 'papier', 'parchemin'],
        kind: 'clue',
        visible: false,
        discovered: false,
        taken: false,
        tags: ['recipe_half', 'quest_item', 'readable'],
        description: 'Un second fragment de recette glisse sous une pile de linges.',
        readableText: 'La seconde moitie parle d une pate qui ne doit jamais etre laissee seule devant un gobelin.',
      },
      grukk_chest: {
        id: 'grukk_chest',
        roomId: '9',
        name: 'coffre de Grukk',
        aliases: ['coffre', 'malle', 'coffre du chef'],
        kind: 'container',
        visible: true,
        discovered: true,
        opened: false,
        locked: true,
        contains: ['goblin_note'],
        tags: ['container', 'boss'],
        dc: { unlock: 13, force: 15 },
        description: 'Un petit coffre brutalement marque par le symbole de Grukk.',
      },
      goblin_note: {
        id: 'goblin_note',
        roomId: '9',
        name: 'note de Grukk',
        aliases: ['note', 'ordre', 'papier de grukk'],
        kind: 'clue',
        visible: false,
        discovered: false,
        taken: false,
        tags: ['readable', 'boss_hint'],
        description: 'Une note ecrite dans un commun agressif.',
        readableText: 'Grukk veut les deux morceaux de recette avant le prochain coucher de soleil.',
      },
    },
    npcs: {
      mac: {
        id: 'mac',
        name: 'Mac',
        roomId: '1',
        aliases: ['pommier', 'treant', 'arbre', 'grand pommier'],
        disposition: 'neutral',
        known: true,
        faction: 'bakery_allies',
        goals: ['proteger Grammy', 'orienter les visiteurs bienveillants', 'eviter que les gobelins emportent la recette'],
        tags: ['bakery', 'quest_giver'],
        memory: {},
      },
      dryad_orchard: {
        id: 'dryad_orchard',
        name: 'druidesse du verger',
        roomId: '2',
        aliases: ['dryade', 'druidesse', 'fee', 'femme du verger'],
        disposition: 'neutral',
        known: false,
        faction: 'orchard_spirits',
        goals: ['preserver le verger', 'tester les intentions du joueur', 'signaler les routes discretes aux allies prudents'],
        tags: ['orchard', 'spirit', 'route_hint'],
        memory: {},
      },
      grukk: {
        id: 'grukk',
        name: 'Grukk',
        roomId: '9',
        aliases: ['chef grukk', 'chef', 'hobgobelin'],
        disposition: 'hostile',
        known: false,
        faction: 'goblin_raiders',
        goals: ['recuperer la recette complete', 'maintenir la pression dans l appartement', 'faire monter l alerte si on le menace sans avantage'],
        tags: ['goblin', 'boss'],
        memory: {},
      },
    },
    quests: {
      grammy_recipe: {
        id: 'grammy_recipe',
        name: 'Retrouver la recette de Grammy',
        progress: 0,
        goal: 2,
        completed: false,
        flags: {},
      },
    },
    alarms: {
      bakery_alert: {
        level: 0,
        raised: false,
        clock: {
          id: 'bakery_alert_clock',
          name: 'Alerte gobeline',
          value: 0,
          thresholds: {
            stirring: 1,
            hunting: 2,
            lockdown: 3,
          },
        },
      },
    },
    flags: {},
    eventLog: [],
  }
}
